/**
 * Authorization API
 * Authorization API
 *
 * OpenAPI spec version: 9.0.000.00.598
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiResponseStatus', 'model/CollectionApiResponseDomainLookupResult', 'model/DomainLookupResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApiResponseStatus'), require('./CollectionApiResponseDomainLookupResult'), require('./DomainLookupResult'));
  } else {
    // Browser globals (root is window)
    if (!root.AuthorizationApi) {
      root.AuthorizationApi = {};
    }
    root.AuthorizationApi.ApiResponseDomainLookupResult = factory(root.AuthorizationApi.ApiClient, root.AuthorizationApi.ApiResponseStatus, root.AuthorizationApi.CollectionApiResponseDomainLookupResult, root.AuthorizationApi.DomainLookupResult);
  }
}(this, function(ApiClient, ApiResponseStatus, CollectionApiResponseDomainLookupResult, DomainLookupResult) {
  'use strict';




  /**
   * The ApiResponseDomainLookupResult model module.
   * @module model/ApiResponseDomainLookupResult
   * @version 9.0.000.00.598
   */

  /**
   * Constructs a new <code>ApiResponseDomainLookupResult</code>.
   * @alias module:model/ApiResponseDomainLookupResult
   * @class
   * @param status {module:model/ApiResponseStatus} 
   */
  var exports = function(status) {
    var _this = this;




    _this['status'] = status;
  };

  /**
   * Constructs a <code>ApiResponseDomainLookupResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiResponseDomainLookupResult} obj Optional instance to populate.
   * @return {module:model/ApiResponseDomainLookupResult} The populated <code>ApiResponseDomainLookupResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = DomainLookupResult.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('errors')) {
        obj['errors'] = CollectionApiResponseDomainLookupResult.constructFromObject(data['errors']);
      }
      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiResponseStatus.constructFromObject(data['status']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DomainLookupResult} data
   */
  exports.prototype['data'] = undefined;
  /**
   * @member {module:model/CollectionApiResponseDomainLookupResult} errors
   */
  exports.prototype['errors'] = undefined;
  /**
   * @member {String} path
   */
  exports.prototype['path'] = undefined;
  /**
   * @member {module:model/ApiResponseStatus} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


