/**
 * Authorization API
 * Authorization API
 *
 * OpenAPI spec version: 9.0.000.00.598
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangePasswordOperation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChangePasswordOperation'));
  } else {
    // Browser globals (root is window)
    if (!root.AuthorizationApi) {
      root.AuthorizationApi = {};
    }
    root.AuthorizationApi.ApiRequestChangePasswordOperation = factory(root.AuthorizationApi.ApiClient, root.AuthorizationApi.ChangePasswordOperation);
  }
}(this, function(ApiClient, ChangePasswordOperation) {
  'use strict';




  /**
   * The ApiRequestChangePasswordOperation model module.
   * @module model/ApiRequestChangePasswordOperation
   * @version 9.0.000.00.598
   */

  /**
   * Constructs a new <code>ApiRequestChangePasswordOperation</code>.
   * @alias module:model/ApiRequestChangePasswordOperation
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ApiRequestChangePasswordOperation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiRequestChangePasswordOperation} obj Optional instance to populate.
   * @return {module:model/ApiRequestChangePasswordOperation} The populated <code>ApiRequestChangePasswordOperation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ChangePasswordOperation.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('operationId')) {
        obj['operationId'] = ApiClient.convertToType(data['operationId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ChangePasswordOperation} data
   */
  exports.prototype['data'] = undefined;
  /**
   * Used for asynchronous operations to map request and response
   * @member {String} operationId
   */
  exports.prototype['operationId'] = undefined;



  return exports;
}));


