/**
 * Authentication API
 * Authentication API
 *
 * OpenAPI spec version: 9.0.000.10.1112
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AuthenticationApi) {
      root.AuthenticationApi = {};
    }
    root.AuthenticationApi.JwtConvertResult = factory(root.AuthenticationApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The JwtConvertResult model module.
   * @module model/JwtConvertResult
   * @version 9.0.000.10.1112
   */

  /**
   * Constructs a new <code>JwtConvertResult</code>.
   * @alias module:model/JwtConvertResult
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>JwtConvertResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JwtConvertResult} obj Optional instance to populate.
   * @return {module:model/JwtConvertResult} The populated <code>JwtConvertResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('jwtToken')) {
        obj['jwtToken'] = ApiClient.convertToType(data['jwtToken'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} jwtToken
   */
  exports.prototype['jwtToken'] = undefined;



  return exports;
}));


