/**
 * Authentication API
 * Authentication API
 *
 * OpenAPI spec version: 9.0.000.44.1858
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.5
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChangePasswordOperation'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChangePasswordOperation'));
  } else {
    // Browser globals (root is window)
    if (!root.AuthenticationApi) {
      root.AuthenticationApi = {};
    }
    root.AuthenticationApi.ApiRequestOfChangePasswordOperation = factory(root.AuthenticationApi.ApiClient, root.AuthenticationApi.ChangePasswordOperation);
  }
}(this, function(ApiClient, ChangePasswordOperation) {
  'use strict';




  /**
   * The ApiRequestOfChangePasswordOperation model module.
   * @module model/ApiRequestOfChangePasswordOperation
   * @version 9.0.000.44.1858
   */

  /**
   * Constructs a new <code>ApiRequestOfChangePasswordOperation</code>.
   * @alias module:model/ApiRequestOfChangePasswordOperation
   * @class
   * @param data {module:model/ChangePasswordOperation} 
   */
  var exports = function(data) {
    var _this = this;

    _this['data'] = data;

  };

  /**
   * Constructs a <code>ApiRequestOfChangePasswordOperation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApiRequestOfChangePasswordOperation} obj Optional instance to populate.
   * @return {module:model/ApiRequestOfChangePasswordOperation} The populated <code>ApiRequestOfChangePasswordOperation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = ChangePasswordOperation.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('operationId')) {
        obj['operationId'] = ApiClient.convertToType(data['operationId'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/ChangePasswordOperation} data
   */
  exports.prototype['data'] = undefined;
  /**
   * Used for asynchronous operations to map request and response
   * @member {String} operationId
   */
  exports.prototype['operationId'] = undefined;



  return exports;
}));


