/**
 * Authorization API
 * Authorization API
 *
 * OpenAPI spec version: 9.0.000.00.598
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApiRequestBaseClientDetails', 'model/ApiRequestChangePasswordOperation', 'model/ApiRequestDomainLookupOperation', 'model/ApiResponse', 'model/ApiResponseDomainLookupResult', 'model/ApiResponseListClientDetails', 'model/ApiResponseStatus', 'model/Authentication', 'model/BaseClientDetails', 'model/ChangePasswordOperation', 'model/ClientDetails', 'model/CloudUserDetails', 'model/CollectionApiResponse', 'model/CollectionApiResponseDomainLookupResult', 'model/CollectionApiResponseListClientDetails', 'model/CollectionGrantedAuthority', 'model/CollectionUserRole', 'model/Collectionstring', 'model/DefaultOAuth2AccessToken', 'model/DomainLookupOperation', 'model/DomainLookupResult', 'model/ErrorResponse', 'model/GWSRequestContext', 'model/GrantedAuthority', 'model/ResponseEntity', 'model/UserRole', 'api/AuthServerApi', 'api/ClientAPIApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/ApiRequestBaseClientDetails'), require('./model/ApiRequestChangePasswordOperation'), require('./model/ApiRequestDomainLookupOperation'), require('./model/ApiResponse'), require('./model/ApiResponseDomainLookupResult'), require('./model/ApiResponseListClientDetails'), require('./model/ApiResponseStatus'), require('./model/Authentication'), require('./model/BaseClientDetails'), require('./model/ChangePasswordOperation'), require('./model/ClientDetails'), require('./model/CloudUserDetails'), require('./model/CollectionApiResponse'), require('./model/CollectionApiResponseDomainLookupResult'), require('./model/CollectionApiResponseListClientDetails'), require('./model/CollectionGrantedAuthority'), require('./model/CollectionUserRole'), require('./model/Collectionstring'), require('./model/DefaultOAuth2AccessToken'), require('./model/DomainLookupOperation'), require('./model/DomainLookupResult'), require('./model/ErrorResponse'), require('./model/GWSRequestContext'), require('./model/GrantedAuthority'), require('./model/ResponseEntity'), require('./model/UserRole'), require('./api/AuthServerApi'), require('./api/ClientAPIApi'));
  }
}(function(ApiClient, ApiRequestBaseClientDetails, ApiRequestChangePasswordOperation, ApiRequestDomainLookupOperation, ApiResponse, ApiResponseDomainLookupResult, ApiResponseListClientDetails, ApiResponseStatus, Authentication, BaseClientDetails, ChangePasswordOperation, ClientDetails, CloudUserDetails, CollectionApiResponse, CollectionApiResponseDomainLookupResult, CollectionApiResponseListClientDetails, CollectionGrantedAuthority, CollectionUserRole, Collectionstring, DefaultOAuth2AccessToken, DomainLookupOperation, DomainLookupResult, ErrorResponse, GWSRequestContext, GrantedAuthority, ResponseEntity, UserRole, AuthServerApi, ClientAPIApi) {
  'use strict';

  /**
   * Authorization_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var AuthorizationApi = require('index'); // See note below*.
   * var xxxSvc = new AuthorizationApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new AuthorizationApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new AuthorizationApi.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new AuthorizationApi.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 9.0.000.00.598
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The ApiRequestBaseClientDetails model constructor.
     * @property {module:model/ApiRequestBaseClientDetails}
     */
    ApiRequestBaseClientDetails: ApiRequestBaseClientDetails,
    /**
     * The ApiRequestChangePasswordOperation model constructor.
     * @property {module:model/ApiRequestChangePasswordOperation}
     */
    ApiRequestChangePasswordOperation: ApiRequestChangePasswordOperation,
    /**
     * The ApiRequestDomainLookupOperation model constructor.
     * @property {module:model/ApiRequestDomainLookupOperation}
     */
    ApiRequestDomainLookupOperation: ApiRequestDomainLookupOperation,
    /**
     * The ApiResponse model constructor.
     * @property {module:model/ApiResponse}
     */
    ApiResponse: ApiResponse,
    /**
     * The ApiResponseDomainLookupResult model constructor.
     * @property {module:model/ApiResponseDomainLookupResult}
     */
    ApiResponseDomainLookupResult: ApiResponseDomainLookupResult,
    /**
     * The ApiResponseListClientDetails model constructor.
     * @property {module:model/ApiResponseListClientDetails}
     */
    ApiResponseListClientDetails: ApiResponseListClientDetails,
    /**
     * The ApiResponseStatus model constructor.
     * @property {module:model/ApiResponseStatus}
     */
    ApiResponseStatus: ApiResponseStatus,
    /**
     * The Authentication model constructor.
     * @property {module:model/Authentication}
     */
    Authentication: Authentication,
    /**
     * The BaseClientDetails model constructor.
     * @property {module:model/BaseClientDetails}
     */
    BaseClientDetails: BaseClientDetails,
    /**
     * The ChangePasswordOperation model constructor.
     * @property {module:model/ChangePasswordOperation}
     */
    ChangePasswordOperation: ChangePasswordOperation,
    /**
     * The ClientDetails model constructor.
     * @property {module:model/ClientDetails}
     */
    ClientDetails: ClientDetails,
    /**
     * The CloudUserDetails model constructor.
     * @property {module:model/CloudUserDetails}
     */
    CloudUserDetails: CloudUserDetails,
    /**
     * The CollectionApiResponse model constructor.
     * @property {module:model/CollectionApiResponse}
     */
    CollectionApiResponse: CollectionApiResponse,
    /**
     * The CollectionApiResponseDomainLookupResult model constructor.
     * @property {module:model/CollectionApiResponseDomainLookupResult}
     */
    CollectionApiResponseDomainLookupResult: CollectionApiResponseDomainLookupResult,
    /**
     * The CollectionApiResponseListClientDetails model constructor.
     * @property {module:model/CollectionApiResponseListClientDetails}
     */
    CollectionApiResponseListClientDetails: CollectionApiResponseListClientDetails,
    /**
     * The CollectionGrantedAuthority model constructor.
     * @property {module:model/CollectionGrantedAuthority}
     */
    CollectionGrantedAuthority: CollectionGrantedAuthority,
    /**
     * The CollectionUserRole model constructor.
     * @property {module:model/CollectionUserRole}
     */
    CollectionUserRole: CollectionUserRole,
    /**
     * The Collectionstring model constructor.
     * @property {module:model/Collectionstring}
     */
    Collectionstring: Collectionstring,
    /**
     * The DefaultOAuth2AccessToken model constructor.
     * @property {module:model/DefaultOAuth2AccessToken}
     */
    DefaultOAuth2AccessToken: DefaultOAuth2AccessToken,
    /**
     * The DomainLookupOperation model constructor.
     * @property {module:model/DomainLookupOperation}
     */
    DomainLookupOperation: DomainLookupOperation,
    /**
     * The DomainLookupResult model constructor.
     * @property {module:model/DomainLookupResult}
     */
    DomainLookupResult: DomainLookupResult,
    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse: ErrorResponse,
    /**
     * The GWSRequestContext model constructor.
     * @property {module:model/GWSRequestContext}
     */
    GWSRequestContext: GWSRequestContext,
    /**
     * The GrantedAuthority model constructor.
     * @property {module:model/GrantedAuthority}
     */
    GrantedAuthority: GrantedAuthority,
    /**
     * The ResponseEntity model constructor.
     * @property {module:model/ResponseEntity}
     */
    ResponseEntity: ResponseEntity,
    /**
     * The UserRole model constructor.
     * @property {module:model/UserRole}
     */
    UserRole: UserRole,
    /**
     * The AuthServerApi service constructor.
     * @property {module:api/AuthServerApi}
     */
    AuthServerApi: AuthServerApi,
    /**
     * The ClientAPIApi service constructor.
     * @property {module:api/ClientAPIApi}
     */
    ClientAPIApi: ClientAPIApi
  };

  return exports;
}));
